framework:
    messenger:
        default_bus: app.command_bus

        buses:
            app.command_bus:
                middleware:
                    - doctrine_transaction
            app.event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_transaction